image:
  file: .gitpod.Dockerfile
tasks:
    - init: echo "Replace me with a build script for the project."
      command: mkdir -p /workspace/data && mongod --dbpath /workspace/data --fork --logpath /workspace/data/mongod.log
    - init: |
        npm install
        gp sync-done installation
      command: npm run server
    - init: gp sync-await installation
      command: npm run client
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
